/**
 * FreshPrint Code Test - OpenAPI 3.0
 * FreshPrint Coding Round Test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: diptaspanda@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    id?: number;
    name: string;
    login?: string;
    avatarUrl?: string;
    reposUrl?: string;
}